- name: Run Mariadb
  community.docker.docker_compose_v2:
    services: mariadb
    wait: true
    wait_timeout: 60
    state: present
    build: policy
    remove_orphans: true
    project_src: "{{ ansible_env.HOME }}/site"
  tags:
    - mariadb
    - services
