- name: Build Mariadb
  command: docker compose build --no-cache mariadb
  args:
    chdir: site
  tags:
    - mariadb
    - services

- name: Run Mariadb
  command: docker compose up -d --remove-orphans --wait --wait-timeout 60 --pull never mariadb
  args:
    chdir: site
  tags:
    - mariadb
    - services
