- name: Install docker dependencies
  become: true
  apt:
    name: 
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: true

- name: Add Docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Set up nginx configuation directory
  become: true
  file:
    path: "{{ nginx_dockerfile_path }}"
    state: directory
    owner: fumon
    group: fumon
    mode: 0755

- name: Pasar un template al asunto
  template:
    src: Dockerfile.j2
    dest: "{{ nginx_dockerfile_path }}Dockerfile"
    owner: fumon
    group: fumon
    mode: 0755

- name: Provide nginx configuration file to host
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_dockerfile_path }}"

- name: Debug var
  debug:
    msg: Hola, "{{ nginx_dockerfile_path }}"

- name: Copy nginx resources into node
  copy:
    owner: fumon
    group: fumon
    mode: 0755
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "cert.pem", dest: "{{ nginx_dockerfile_path }}"}
    - {src: "key.pem", dest: "{{ nginx_dockerfile_path }}"}
    - {src: "entrypoint.sh", dest: "{{ nginx_dockerfile_path }}"}

- name: Complex command execution
  command:
    cmd: echo hola && echo hola && echo hola | cat | cat | cat -e

- name: Enchufar usuario a grupo docker
  become: true
  user:
    name: fumon
    groups: docker
    append: yes

- name: Build nginx image
  become: true
  community.docker.docker_image_build:
    path: "{{ nginx_dockerfile_path }}"
    name: cloud1-nginx
