- name: Copy Docs In Remote
  synchronize:
    src: files/markdown/
    dest: "{{ ansible_env.HOME }}/markdown"
    delete: false
    recursive: true
  tags:
    - common

- name: Build The Doc
  shell: mkdocs build
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/markdown"

- name: Copy Site In Remote
  synchronize:
    src: files/site/
    dest: "{{ ansible_env.HOME }}/site"
    delete: true
    recursive: true
  tags:
    - common

- name: Actualize Env File With Host IP
  shell: echo "SITE_HOSTNAME={{ ansible_host }}" >> .env
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/site"
