- name: Copy Site In Remote
  synchronize:
    src: files/site/
    dest: "{{ ansible_env.HOME }}/site"
    delete: true
    recursive: true
  tags:
    - common

- name: Actualize Env File With Host IP
  shell: echo "SITE_HOSTNAME={{ ansible_host }}" >> .env
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/site"
