services:
  node1:
    container_name: node_1
    build: 
      context: .
      args:
        SSH_USER: ${SSH_USER}
        ROOT_PWD: ${ROOT_PASSWORD}
    networks:
      nw:
        ipv4_address: 10.2.0.2
  node2:
    container_name: node_2
    build: 
      context: .
      args:
        SSH_USER: ${SSH_USER}
        ROOT_PWD: ${ROOT_PASSWORD}
    networks:
      nw:
        ipv4_address: 10.2.0.4        

  terraform_node:
    container_name: terraform
    command: sleep infinity
    build:
      context: .
      dockerfile: terraform.Dockerfile
    networks:
      nw:


networks:
  nw:
    driver: bridge
    ipam:
      config:
      - subnet: 10.2.0.0/24
