services:
  host1:
    hostname: host1
    image: host1
    container_name: host1
    build: .
    networks:
      network1:
        ipv4_address: 10.5.0.2

  host2:
    hostname: host2
    image: host2
    container_name: host2
    build: .
    networks:
      network1:
        ipv4_address: 10.5.0.3

  host3:
    hostname: host3
    image: host3
    container_name: host3
    build: .
    networks:
      network1:
        ipv4_address: 10.5.0.4
      
networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
