- name: Playbook test execution (comm. with local nodes)
  hosts: localhosts
  remote_user: fumon

  tasks:
  - name: First of all, un ping
    ansible.builtin.ping:

  - name: Then, copy a file
    copy:
      src: ./Dockerfile
      dest: /tmp/dir/Dockerfile
      mode: 644


# comprobamos que el Dockerfile existe en los nodos
  - name: Last but not least, custom logic with script