FROM {{ base_image }}

ARG SSL_CERT SSL_CERT_KEY
ENV SSL_CERT={{ ssl_cert }}
ENV SSL_CERT_KEY={{ ssl_cert_key }}

RUN apt-get update && apt-get install -y --no-install-recommends \
    nginx \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /
RUN chmod +x entrypoint.sh

COPY nginx.conf /etc/nginx/
COPY {{ ssl_cert }} /etc/ssl/
COPY {{ ssl_cert_key }} /etc/ssl/

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]