- name: Run Nginx
  community.docker.docker_compose_v2:
    services: nginx
    wait: true
    wait_timeout: 60
    state: present
    build: always
    remove_orphans: true
    project_src: "{{ ansible_env.HOME }}/site"
  tags:
    - nginx
    - services
