- name: Build Nginx
  command: docker compose build --no-cache nginx
  args:
    chdir: site
  tags:
    - nginx
    - services

- name: Run Nginx
  command: docker compose up -d --remove-orphans --wait --wait-timeout 60 --pull never nginx
  args:
    chdir: site
  tags:
    - nginx
    - services
