- name: Run Mariadb
  community.docker.docker_compose_v2:
    services: mariadb
    wait: true
    state: present
    build: always
    remove_orphans: true
    project_src: "{{ ansible_env.HOME }}/site"
