- name: Build Redis
  command: docker compose build --no-cache redis
  args:
    chdir: site
  tags:
    - redis
    - services

- name: Run Redis
  command: docker compose up -d --remove-orphans --wait --wait-timeout 60 --pull never redis
  args:
    chdir: site
  tags:
    - redis
    - services
