- name: Run Go Server
  community.docker.docker_compose_v2:
    services: server
    wait: true
    wait_timeout: 60
    state: present
    build: always
    remove_orphans: true
    project_src: "{{ ansible_env.HOME }}/site"
  tags:
    - server
    - services
