services:
  mariadb:
    hostname: mariadb
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - network1
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER?error}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?error}
      - MYSQL_USER=${MYSQL_USER?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?error}
      - NETWORK_NAME=${NETWORK_NAME?error}
    healthcheck:
      test: ["CMD", "/healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mariadb_volume:/var/lib/mysql

  redis:
    hostname: redis
    image: redis
    container_name: redis
    build: ./requirements/redis
    restart: always
    networks:
      - network1
    healthcheck:
      test: ["CMD", "/redis-cli", "ping"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    hostname: wordpress
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - network1
    environment:
      - SITE_HOSTNAME=${SITE_HOSTNAME?error}
      - MYSQL_USER=${MYSQL_USER?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?error}
      - FCGI_CONNECT=wordpress:9000
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/php-fpm-healthcheck"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - wordpress_volume:/srv/www/wordpress/

  nginx:
    hostname: nginx
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - SSL_CERT=${SSL_CERT?error}
        - SSL_CERT_KEY=${SSL_CERT_KEY?error}
    restart: always
    ports:
      - "443:443"
    networks:
      - network1
    environment:
      - SSL_PASSWORD=${SSL_PASSWORD?error}
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://nginx"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - wordpress_volume:/srv/www/wordpress/

networks:
  network1:
    name: ${NETWORK_NAME?error}

volumes:
  wordpress_volume:
    name: ${WORDPRESS_VOLUME?error}
  mariadb_volume:
    name: ${MARIADB_VOLUME?error}
