- name: Generate Inventory 
  hosts: localhost
  gather_facts: false
  vars:
    addresses: "{{ lookup('file', 'hosts.dat').splitlines() }}"
  tasks:
    - name: Template inventory
      add_host:
        name: "{{ item }}"
        groups: remote
        ansible_user: fumon
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop: "{{ addresses }}"
  tags:
    - always

- name: Set Up Machine
  hosts: remote
  roles:
    - common
    - mariadb
    - redis
    - wordpress
    - nginx
