- name: Run php-fpm
  community.docker.docker_compose_v2:
    services: wordpress
    wait: true
    wait_timeout: 60
    state: present
    build: policy
    remove_orphans: true
    project_src: "{{ ansible_env.HOME }}/site"
  tags:
    - wordpress
    - services
