- name: Build Wordpress
  command: docker compose build --no-cache wordpress
  args:
    chdir: site
  tags:
    - wordpress
    - services

- name: Run Wordpress
  command: docker compose up -d --remove-orphans --wait --wait-timeout 60 --pull never wordpress
  args:
    chdir: site
  tags:
    - wordpress
    - services
